ALTER TABLE fixations
ALTER COLUMN "diameter" TYPE INTEGER,
ALTER COLUMN "drill_diameter" TYPE INTEGER;

ALTER TABLE materials
ALTER COLUMN "min_width" TYPE INTEGER,
ALTER COLUMN "min_height" TYPE INTEGER,
ALTER COLUMN "max_width" TYPE INTEGER,
ALTER COLUMN "max_height" TYPE INTEGER,
ALTER COLUMN "weight" TYPE INTEGER;

ALTER TABLE fixation_conditions
ALTER COLUMN "padding_h" TYPE INTEGER,
ALTER COLUMN "padding_v" TYPE INTEGER;

ALTER TABLE dimensions
ALTER COLUMN "width" TYPE INTEGER,
ALTER COLUMN "height" TYPE INTEGER;
